#include <stdio.h>
/**
 * main - Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2
 * Fibonacci sequence values not exceed 4,000,000
 *
 * Return:0
 */
int main(void)
{
	long pri = 0, sec = 1, sum;

	sum = pri + sec;
	while (sum <= 4000000)
	{
		if (sum % 2 != 0)
		{
		sum = pri + sec;
		pri = sec;
	}
	printf("%lu\n", sum);
	}
	return (0);
}
